# Generated by Django 2.0.6 on 2019-10-14 18:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wikiApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewEntryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Entry_Title', models.CharField(max_length=100)),
                ('Entry_Text', models.CharField(max_length=10000)),
                ('Entry_Date', models.DateTimeField(default=datetime.datetime(2019, 10, 14, 18, 47, 30, 84766, tzinfo=utc))),
                ('Entry_FileUpload', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
    ]
