# Generated by Django 2.0.6 on 2019-10-16 19:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wikiApp', '0002_newentrymodel_relatedentrymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newentrymodel',
            name='Entry_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 19, 36, 26, 438138, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='newentrymodel',
            name='Entry_FileUpload',
            field=models.ImageField(blank=True, null=True, upload_to='wikiApp/'),
        ),
        migrations.AlterField(
            model_name='relatedentrymodel',
            name='Related_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 19, 36, 26, 438799, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='relatedentrymodel',
            name='Related_FileUpload',
            field=models.ImageField(blank=True, null=True, upload_to='wikiApp/'),
        ),
    ]
