# Generated by Django 2.0.6 on 2019-10-14 19:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wikiApp', '0002_newentrymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newentrymodel',
            name='Entry_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 14, 19, 56, 57, 450555, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='newentrymodel',
            name='Entry_Text',
            field=models.TextField(max_length=10000),
        ),
    ]
