# Generated by Django 2.0.6 on 2019-10-14 20:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wikiApp', '0003_auto_20191014_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newentrymodel',
            name='Entry_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 14, 20, 27, 14, 696032, tzinfo=utc)),
        ),
    ]
