# Generated by Django 2.0.6 on 2019-10-14 20:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wikiApp', '0004_auto_20191014_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newentrymodel',
            name='Entry_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 14, 20, 50, 48, 251533, tzinfo=utc)),
        ),
    ]
