# Generated by Django 2.0.6 on 2019-10-15 05:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wikiApp', '0005_auto_20191014_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newentrymodel',
            name='Entry_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 15, 5, 20, 50, 456150, tzinfo=utc)),
        ),
    ]
