# Generated by Django 2.0.6 on 2019-12-03 05:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wikiApp', '0005_auto_20191016_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newentrymodel',
            name='Entry_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 3, 5, 5, 41, 639302, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='relatedentrymodel',
            name='Related_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 3, 5, 5, 41, 640073, tzinfo=utc)),
        ),
    ]
